google_project_id       = "orbital-lantern-320420"
google_bucket_name      = "fuchicorp-salta-bucket"
deployment_environment  = "prod"
deployment_name         = "hello-world"
google_credentials_json = "fuchicorp-service-account.json"
